apiVersion : apps/v1
kind: Deployment
metadata:
  name: {{ include "prefect-agent.fullname" . }}-agent
  labels:
    {{- include "prefect-agent.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "prefect-agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.agent.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "prefect-agent.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.agent.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "prefect-agent.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.agent.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.agent.securityContext | nindent 12 }}
          image: "{{ .Values.agent.image.name }}:{{ .Values.agent.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.agent.image.pullPolicy }}
          command: ["prefect", "agent", "start", {{ .Values.agent.workQueueName }}]
          env:
          {{- if .Values.agent.serverUrl  }}
          - name: PREFECT_API_URL
            value: {{ .Values.agent.serverUrl }}
          {{- else }}
          - name: PREFECT_API_URL
            value: 
          {{- end }}
          resources:
            {{- toYaml .Values.agent.resources | nindent 12 }}
      {{- with .Values.agent.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.agent.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.agent.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
