{{- if .Values.api.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "orion.fullname" . }}
  labels:
    {{- include "orion.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      protocol: TCP
  selector:
    {{- include "orion.selectorLabels" . | nindent 4 }}
{{- end }}