
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "prefect-agent.serviceAccountName" . }}
  labels:
{{- include "prefect-agent.commonLabels" . | nindent 4 }}
  annotations:
    {{- merge .Values.serviceAccount.annotations .Values.annotations | toYaml | nindent 4 }}
{{- end -}}